# Task for SQL DML session

Load this dataset in your database and perform below given tasks.

DataSet - https://docs.google.com/spreadsheets/d/e/2PACX-1vRa1wWwXmzxEvqITxj4OQTeLywlGTTsOTbhSRqKj2lPuGefjlci-DQhgLBPpgWXe8AAUu2WUBqY59X1/pub?gid=1030172542&single=true&output=csv

Look for data description

Kaggle - https://www.kaggle.com/datasets/thedevastator/insurance-claim-analysis-demographic-and-health?select=insurance_data.csv

### Perform the following queries

1. Show records of 'male' patient from 'southwest' region.
2. Show all records having bmi in range 30 to 45 both inclusive.
3. Show minimum and maximum bloodpressure of diabetic patient who smokes. Make column names as MinBP and MaxBP respectively.
4. Find no of unique patients who are not from southwest region.
5. Total claim amount from male smoker.
6. Select all records of south region.
7. No of patient having normal blood pressure. Normal range[90-120]
8. No of pateint belo 17 years of age having normal blood pressure as per below formula -
    - BP normal range = 80+(age in years × 2) to 100 + (age in years × 2)

    - Note: Formula taken just for practice, don't take in real sense.
9. What is the average claim amount for non-smoking female patients who are diabetic?
10. Write a SQL query to update the claim amount for the patient with PatientID = 1234 to 5000.
11. Write a SQL query to delete all records for patients who are smokers and have no children.

In [1]:
import numpy as np
import pandas as pd

In [2]:
import mysql.connector

In [3]:
con = mysql.connector.connect(host='localhost',port='3307',user='root',password='',database='task32')

In [4]:
import pymysql
from sqlalchemy import create_engine

In [5]:
insurance_data =pd.read_csv("insurance_data.csv")
insurance_data

,index,PatientID,age,gender,bmi,bloodpressure,diabetic,children,smoker,region,claim
0,0,1,39.0,male,23.2,91,Yes,0,No,southeast,1121.87
1,1,2,24.0,male,30.1,87,No,0,No,southeast,1131.51
2,2,3,NaN,male,33.3,82,Yes,0,No,southeast,1135.94
3,3,4,NaN,male,33.7,80,No,0,No,northwest,1136.40
4,4,5,NaN,male,34.1,100,No,0,No,northwest,1137.01
...,...,...,...,...,...,...,...,...,...,...,...
1335,1335,1336,44.0,female,35.5,88,Yes,0,Yes,northwest,55135.40
1336,1336,1337,59.0,female,38.1,120,No,1,Yes,northeast,58571.07
1337,1337,1338,30.0,male,34.5,91,Yes,3,Yes,northwest,60021.40
1338,1338,1339,37.0,male,30.4,106,No,0,Yes,southeast,62592.87
1339,1339,1340,30.0,female,47.4,101,No,0,Yes,southeast,63770.43

In [7]:
engine = create_engine("mysql+pymysql://root:@localhost:3307/task32")
# {root}:{password}@{url}/{database}
insurance_data.to_sql('insurance_data', con = engine, if_exists = 'append')

1340

In [8]:
df = pd.read_sql_query("SELECT * FROM insurance_data",con)
df

C:\Users\Administrator\anaconda3\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

,level_0,index,PatientID,age,gender,bmi,bloodpressure,diabetic,children,smoker,region,claim
0,0,0,1,39.0,male,23.2,91,Yes,0,No,southeast,1121.87
1,1,1,2,24.0,male,30.1,87,No,0,No,southeast,1131.51
2,2,2,3,NaN,male,33.3,82,Yes,0,No,southeast,1135.94
3,3,3,4,NaN,male,33.7,80,No,0,No,northwest,1136.40
4,4,4,5,NaN,male,34.1,100,No,0,No,northwest,1137.01
...,...,...,...,...,...,...,...,...,...,...,...,...
1335,1335,1335,1336,44.0,female,35.5,88,Yes,0,Yes,northwest,55135.40
1336,1336,1336,1337,59.0,female,38.1,120,No,1,Yes,northeast,58571.07
1337,1337,1337,1338,30.0,male,34.5,91,Yes,3,Yes,northwest,60021.40
1338,1338,1338,1339,37.0,male,30.4,106,No,0,Yes,southeast,62592.87
1339,1339,1339,1340,30.0,female,47.4,101,No,0,Yes,southeast,63770.43

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   level_0        1340 non-null   int64
 1   index          1340 non-null   object
 2   PatientID      1340 non-null   int64
 3   age            1340 non-null   object
 4   gender         1340 non-null   object
 5   bmi            1340 non-null   object
 6   bloodpressure  1340 non-null   object
 7   diabetic       1340 non-null   object
 8   children       1340 non-null   object
 9   smoker         1340 non-null   object
 10  region         1340 non-null   object
 11  claim          1340 non-null   object
dtypes: int64(2), object(10)
memory usage: 125.8+ KB

In [20]:
df.shape[0]

1340

## Q1 Show records of 'male' patient from 'southwest' region.

In [ ]:
# use this query in sql workbench
# SELECT * FROM insurance_data WHERE gender='male' AND region='southwest';

In [9]:
# create a cursor object
cursor = con.cursor()

# execute the SQL query
cursor.execute("SELECT * FROM insurance_data WHERE gender='male' AND region='southwest'")

# fetch all the records
records = cursor.fetchall()

# print the records
for record in records:
  print(record)

# # close the cursor and connection
# cursor.close()
# con.close()

(16, 16, 17, 35.0, 'male', 34.1, 90, 'No', 0, 'No', 'southwest', 1261.44)
(17, 17, 18, 41.0, 'male', 34.4, 84, 'No', 0, 'No', 'southwest', 1261.86)
(18, 18, 19, 49.0, 'male', 35.4, 97, 'Yes', 0, 'No', 'southwest', 1263.25)
(21, 21, 22, 34.0, 'male', 31.1, 96, 'No', 0, 'No', 'southwest', 1526.31)
(47, 47, 48, 31.0, 'male', 39.5, 80, 'Yes', 0, 'No', 'southwest', 1682.6)
(72, 72, 73, 22.0, 'male', 34.4, 98, 'Yes', 0, 'No', 'southwest', 1826.84)
(73, 73, 74, 20.0, 'male', 20.9, 98, 'No', 1, 'No', 'southwest', 1832.09)
(74, 74, 75, 50.0, 'male', 24.6, 90, 'No', 1, 'No', 'southwest', 1837.24)
(76, 76, 77, 38.0, 'male', 28.4, 87, 'No', 1, 'No', 'southwest', 1842.52)
(84, 84, 85, 36.0, 'male', 22.0, 88, 'Yes', 1, 'No', 'southwest', 1964.78)
(100, 100, 101, 30.0, 'male', 22.3, 83, 'Yes', 1, 'No', 'southwest', 2103.08)
(140, 140, 141, 47.0, 'male', 35.2, 80, 'No', 1, 'No', 'southwest', 2416.96)
(149, 149, 150, 22.0, 'male', 30.5, 82, 'No', 0, 'No', 'southwest', 2494.02)
(183, 183, 184, 37.0, 'male', 27.2, 87, 'Yes', 0, 'No', 'southwest', 2866.09)
(188, 188, 189, 35.0, 'male', 30.0, 86, 'No', 1, 'No', 'southwest', 2904.09)
(213, 213, 214, 35.0, 'male', 20.4, 88, 'No', 0, 'No', 'southwest', 3260.2)
(215, 215, 216, 28.0, 'male', 37.1, 90, 'Yes', 1, 'No', 'southwest', 3277.16)
(228, 228, 229, 40.0, 'male', 34.8, 81, 'No', 3, 'No', 'southwest', 3443.06)
(231, 231, 232, 35.0, 'male', 23.7, 88, 'No', 2, 'No', 'southwest', 3484.33)
(241, 241, 242, 23.0, 'male', 32.7, 82, 'Yes', 3, 'No', 'southwest', 3591.48)
(243, 243, 244, 48.0, 'male', 37.1, 97, 'No', 3, 'No', 'southwest', 3597.6)
(245, 245, 246, 23.0, 'male', 31.4, 88, 'No', 1, 'No', 'southwest', 3659.35)
(246, 246, 247, 20.0, 'male', 45.9, 97, 'No', 2, 'No', 'southwest', 3693.43)
(254, 254, 255, 31.0, 'male', 23.8, 83, 'No', 2, 'No', 'southwest', 3847.67)
(260, 260, 261, 28.0, 'male', 26.8, 92, 'No', 3, 'No', 'southwest', 3906.13)
(277, 277, 278, 26.0, 'male', 31.5, 95, 'Yes', 1, 'No', 'southwest', 4076.5)
(289, 289, 290, 35.0, 'male', 30.3, 80, 'No', 3, 'No', 'southwest', 4260.74)
(301, 301, 302, 26.0, 'male', 31.5, 88, 'Yes', 0, 'No', 'southwest', 4402.23)
(319, 319, 320, 26.0, 'male', 42.9, 95, 'Yes', 1, 'No', 'southwest', 4536.26)
(326, 326, 327, 18.0, 'male', 30.8, 97, 'Yes', 0, 'No', 'southwest', 4646.76)
(329, 329, 330, 22.0, 'male', 35.2, 87, 'Yes', 2, 'No', 'southwest', 4670.64)
(337, 337, 338, 29.0, 'male', 27.1, 82, 'Yes', 1, 'No', 'southwest', 4746.34)
(339, 339, 340, 19.0, 'male', 30.5, 92, 'Yes', 1, 'No', 'southwest', 4751.07)
(341, 341, 342, 46.0, 'male', 38.6, 83, 'Yes', 1, 'No', 'southwest', 4762.33)
(366, 366, 367, 24.0, 'male', 23.9, 84, 'No', 5, 'No', 'southwest', 5080.1)
(378, 378, 379, 23.0, 'male', 30.8, 89, 'Yes', 3, 'No', 'southwest', 5253.52)
(404, 404, 405, 23.0, 'male', 31.0, 90, 'No', 1, 'No', 'southwest', 5488.26)
(407, 407, 408, 31.0, 'male', 24.3, 83, 'Yes', 5, 'No', 'southwest', 5615.37)
(422, 422, 423, 27.0, 'male', 28.9, 94, 'Yes', 3, 'No', 'southwest', 5926.85)
(425, 425, 426, 46.0, 'male', 26.9, 90, 'No', 0, 'No', 'southwest', 5969.72)
(429, 429, 430, 38.0, 'male', 34.1, 90, 'No', 0, 'No', 'southwest', 5979.73)
(431, 431, 432, 38.0, 'male', 29.4, 96, 'No', 4, 'No', 'southwest', 6059.17)
(434, 434, 435, 42.0, 'male', 34.7, 97, 'Yes', 2, 'No', 'southwest', 6082.41)
(447, 447, 448, 45.0, 'male', 23.2, 92, 'No', 0, 'No', 'southwest', 6250.44)
(449, 449, 450, 43.0, 'male', 28.8, 93, 'No', 1, 'No', 'southwest', 6282.24)
(477, 477, 478, 31.0, 'male', 29.9, 99, 'Yes', 2, 'No', 'southwest', 6600.36)
(483, 483, 484, 48.0, 'male', 42.4, 92, 'Yes', 5, 'No', 'southwest', 6666.24)
(495, 495, 496, 46.0, 'male', 30.1, 85, 'Yes', 1, 'No', 'southwest', 6849.03)
(497, 497, 498, 45.0, 'male', 32.2, 100, 'Yes', 2, 'No', 'southwest', 6875.96)
(511, 511, 512, 19.0, 'male', 22.3, 81, 'No', 0, 'No', 'southwest', 7147.11)
(516, 516, 517, 48.0, 'male', 35.8, 82, 'Yes', 2, 'No', 'southwest', 7160.09)
(520, 520, 521, 21.0, 'male', 35.3, 96, 'No', 3, 'No', 'southwest', 7196.87)
(541, 541, 542, 46.0, 'male', 30.2, 80, 'No', 1, 'No', 'southwest', 7441.05)
(542, 542, 543, 19.0, 'male', 32.6, 94, 'Yes', 2, 'No', 'southwest', 7441.5)
(544, 544, 545, 26.0, 'male', 33.7, 92, 'No', 1, 'No', 'southwest', 7445.92)
(546, 546, 547, 31.0, 'male', 29.6, 85, 'No', 4, 'No', 'southwest', 7512.27)
(558, 558, 559, 46.0, 'male', 27.4, 88, 'No', 2, 'No', 'southwest', 7726.85)
(563, 563, 564, 36.0, 'male', 37.1, 90, 'No', 2, 'No', 'southwest', 7740.34)
(575, 575, 576, 42.0, 'male', 28.7, 88, 'No', 2, 'No', 'southwest', 8027.97)
(577, 577, 578, 25.0, 'male', 32.3, 98, 'No', 1, 'No', 'southwest', 8062.76)
(578, 578, 579, 22.0, 'male', 36.2, 100, 'Yes', 1, 'No', 'southwest', 8068.19)
(581, 581, 582, 40.0, 'male', 30.3, 83, 'Yes', 0, 'No', 'southwest', 8116.68)
(605, 605, 606, 45.0, 'male', 26.6, 99, 'No', 0, 'No', 'southwest', 8444.47)
(606, 606, 607, 46.0, 'male', 36.2, 85, 'No', 0, 'No', 'southwest', 8457.82)
(626, 626, 627, 23.0, 'male', 27.5, 97, 'No', 3, 'No', 'southwest', 8615.3)
(630, 630, 631, 26.0, 'male', 28.7, 93, 'No', 1, 'No', 'southwest', 8703.46)
(633, 633, 634, 29.0, 'male', 25.4, 87, 'Yes', 0, 'No', 'southwest', 8782.47)
(634, 634, 635, 29.0, 'male', 37.0, 84, 'Yes', 0, 'No', 'southwest', 8798.59)
(647, 647, 648, 23.0, 'male', 30.2, 95, 'No', 2, 'No', 'southwest', 8968.33)
(655, 655, 656, 34.0, 'male', 36.7, 92, 'No', 0, 'No', 'southwest', 9144.57)
(672, 672, 673, 20.0, 'male', 39.7, 90, 'No', 1, 'No', 'southwest', 9391.35)
(683, 683, 684, 34.0, 'male', 34.3, 105, 'No', 3, 'No', 'southwest', 9563.03)
(689, 689, 690, 48.0, 'male', 32.3, 88, 'Yes', 2, 'No', 'southwest', 9630.4)
(695, 695, 696, 26.0, 'male', 30.2, 99, 'No', 1, 'No', 'southwest', 9724.53)
(700, 700, 701, 46.0, 'male', 31.6, 106, 'No', 0, 'No', 'southwest', 9850.43)
(715, 715, 716, 42.0, 'male', 21.4, 104, 'No', 1, 'No', 'southwest', 10065.41)
(717, 717, 718, 27.0, 'male', 36.1, 104, 'Yes', 1, 'No', 'southwest', 10085.85)
(718, 718, 719, 34.0, 'male', 25.8, 100, 'Yes', 5, 'No', 'southwest', 10096.97)
(726, 726, 727, 30.0, 'male', 29.9, 90, 'No', 0, 'No', 'southwest', 10214.64)
(731, 731, 732, 29.0, 'male', 38.6, 82, 'Yes', 2, 'No', 'southwest', 10325.21)
(739, 739, 740, 37.0, 'male', 29.2, 109, 'No', 1, 'No', 'southwest', 10436.1)
(740, 740, 741, 27.0, 'male', 39.6, 101, 'Yes', 1, 'No', 'southwest', 10450.55)
(745, 745, 746, 40.0, 'male', 22.1, 83, 'Yes', 0, 'No', 'southwest', 10577.09)
(750, 750, 751, 29.0, 'male', 39.6, 92, 'No', 0, 'No', 'southwest', 10601.41)
(752, 752, 753, 40.0, 'male', 40.3, 96, 'No', 0, 'No', 'southwest', 10602.39)
(757, 757, 758, 30.0, 'male', 21.5, 87, 'No', 1, 'No', 'southwest', 10791.96)
(768, 768, 769, 37.0, 'male', 23.7, 91, 'Yes', 0, 'No', 'southwest', 10959.33)
(770, 770, 771, 39.0, 'male', 28.1, 106, 'Yes', 0, 'No', 'southwest', 10965.45)
(788, 788, 789, 31.0, 'male', 28.6, 86, 'No', 3, 'No', 'southwest', 11253.42)
(789, 789, 790, 49.0, 'male', 36.6, 84, 'No', 3, 'No', 'southwest', 11264.54)
(796, 796, 797, 38.0, 'male', 23.3, 98, 'No', 0, 'No', 'southwest', 11345.52)
(799, 799, 800, 30.0, 'male', 35.7, 91, 'No', 0, 'No', 'southwest', 11362.76)
(801, 801, 802, 43.0, 'male', 38.0, 109, 'Yes', 0, 'No', 'southwest', 11365.95)
(818, 818, 819, 18.0, 'male', 43.7, 101, 'No', 1, 'No', 'southwest', 11576.13)
(825, 825, 826, 37.0, 'male', 27.0, 83, 'Yes', 2, 'No', 'southwest', 11737.85)
(857, 857, 858, 23.0, 'male', 28.9, 83, 'Yes', 0, 'No', 'southwest', 12146.97)
(868, 868, 869, 44.0, 'male', 27.5, 104, 'Yes', 1, 'No', 'southwest', 12333.83)
(869, 869, 870, 40.0, 'male', 37.1, 84, 'Yes', 1, 'No', 'southwest', 12347.17)
(870, 870, 871, 33.0, 'male', 36.1, 80, 'Yes', 3, 'No', 'southwest', 12363.55)
(879, 879, 880, 36.0, 'male', 43.4, 96, 'No', 0, 'No', 'southwest', 12574.05)
(901, 901, 902, 19.0, 'male', 21.4, 85, 'Yes', 0, 'No', 'southwest', 12957.12)
(902, 902, 903, 43.0, 'male', 37.4, 81, 'No', 0, 'No', 'southwest', 12979.36)
(921, 921, 922, 27.0, 'male', 30.8, 98, 'No', 0, 'No', 'southwest', 13390.56)
(922, 922, 923, 28.0, 'male', 33.1, 84, 'No', 0, 'No', 'southwest', 13393.76)
(939, 939, 940, 24.0, 'male', 34.5, 95, 'No', 0, 'No', 'southwest', 13822.8)
(964, 964, 965, 44.0, 'male', 32.8, 89, 'Yes', 1, 'No', 'southwest', 14358.36)
(981, 981, 982, 21.0, 'male', 25.6, 95, 'No', 2, 'No', 'southwest', 14988.43)
(985, 985, 986, 24.0, 'male', 39.8, 95, 'Yes', 3, 'No', 'southwest', 15170.07)
(992, 992, 993, 30.0, 'male', 19.3, 84, 'Yes', 0, 'Yes', 'southwest', 15820.7)
(998, 998, 999, 34.0, 'male', 27.3, 89, 'Yes', 0, 'Yes', 'southwest', 16232.85)
(999, 999, 1000, 33.0, 'male', 27.7, 94, 'No', 0, 'Yes', 'southwest', 16297.85)
(1026, 1026, 1027, 36.0, 'male', 25.7, 96, 'Yes', 4, 'Yes', 'southwest', 17942.11)
(1032, 1032, 1033, 22.0, 'male', 24.4, 83, 'Yes', 3, 'Yes', 'southwest', 18259.22)
(1047, 1047, 1048, 27.0, 'male', 27.1, 104, 'No', 1, 'Yes', 'southwest', 19040.88)
(1050, 1050, 1051, 43.0, 'male', 25.9, 81, 'No', 3, 'Yes', 'southwest', 19199.94)
(1065, 1065, 1066, 23.0, 'male', 29.7, 99, 'Yes', 3, 'Yes', 'southwest', 19933.46)
(1074, 1074, 1075, 47.0, 'male', 29.8, 89, 'Yes', 0, 'No', 'southwest', 20420.6)
(1076, 1076, 1077, 19.0, 'male', 37.3, 102, 'Yes', 0, 'No', 'southwest', 20630.28)
(1083, 1083, 1084, 37.0, 'male', 28.3, 109, 'Yes', 1, 'Yes', 'southwest', 21082.16)
(1087, 1087, 1088, 44.0, 'male', 29.6, 91, 'Yes', 0, 'No', 'southwest', 21232.18)
(1097, 1097, 1098, 39.0, 'male', 37.4, 99, 'Yes', 0, 'No', 'southwest', 21797.0)
(1101, 1101, 1102, 40.0, 'male', 30.0, 106, 'No', 0, 'Yes', 'southwest', 22144.03)
(1112, 1112, 1113, 22.0, 'male', 33.1, 91, 'No', 0, 'No', 'southwest', 23082.96)
(1116, 1116, 1117, 42.0, 'male', 25.6, 106, 'Yes', 2, 'Yes', 'southwest', 23306.55)
(1119, 1119, 1120, 44.0, 'male', 28.0, 93, 'No', 1, 'Yes', 'southwest', 23568.27)
(1132, 1132, 1133, 46.0, 'male', 27.6, 84, 'No', 0, 'No', 'southwest', 24603.05)
(1140, 1140, 1141, 19.0, 'male', 29.8, 89, 'No', 3, 'Yes', 'southwest', 25309.49)
(1142, 1142, 1143, 26.0, 'male', 25.1, 85, 'No', 3, 'Yes', 'southwest', 25382.3)
(1165, 1165, 1166, 22.0, 'male', 36.1, 80, 'No', 3, 'No', 'southwest', 27941.29)
(1200, 1200, 1201, 40.0, 'male', 32.7, 98, 'No', 0, 'Yes', 'southwest', 34472.84)
(1203, 1203, 1204, 26.0, 'male', 34.8, 94, 'Yes', 0, 'Yes', 'southwest', 34779.62)
(1205, 1205, 1206, 20.0, 'male', 34.9, 124, 'Yes', 0, 'Yes', 'southwest', 34828.65)
(1210, 1210, 1211, 25.0, 'male', 30.8, 140, 'Yes', 0, 'Yes', 'southwest', 35491.64)
(1211, 1211, 1212, 22.0, 'male', 35.6, 97, 'Yes', 0, 'Yes', 'southwest', 35585.58)
(1214, 1214, 1215, 40.0, 'male', 32.9, 87, 'Yes', 2, 'Yes', 'southwest', 36085.22)
(1218, 1218, 1219, 37.0, 'male', 34.4, 126, 'No', 0, 'Yes', 'southwest', 36197.7)
(1223, 1223, 1224, 20.0, 'male', 35.3, 86, 'No', 0, 'Yes', 'southwest', 36837.47)
(1236, 1236, 1237, 48.0, 'male', 27.8, 81, 'Yes', 0, 'Yes', 'southwest', 37829.72)
(1240, 1240, 1241, 34.0, 'male', 39.4, 85, 'No', 2, 'Yes', 'southwest', 38344.57)
(1241, 1241, 1242, 32.0, 'male', 33.4, 112, 'Yes', 2, 'Yes', 'southwest', 38415.47)
(1244, 1244, 1245, 22.0, 'male', 36.3, 123, 'No', 2, 'Yes', 'southwest', 38711.0)
(1247, 1247, 1248, 26.0, 'male', 30.2, 88, 'No', 2, 'Yes', 'southwest', 38998.55)
(1250, 1250, 1251, 42.0, 'male', 37.8, 106, 'No', 2, 'Yes', 'southwest', 39241.44)
(1256, 1256, 1257, 27.0, 'male', 30.9, 139, 'No', 0, 'Yes', 'southwest', 39727.61)
(1262, 1262, 1263, 30.0, 'male', 35.3, 89, 'No', 2, 'Yes', 'southwest', 40103.89)
(1263, 1263, 1264, 50.0, 'male', 34.1, 86, 'No', 4, 'Yes', 'southwest', 40182.25)
(1285, 1285, 1286, 49.0, 'male', 34.2, 98, 'Yes', 2, 'Yes', 'southwest', 42856.84)
(1300, 1300, 1301, 29.0, 'male', 35.5, 98, 'No', 2, 'Yes', 'southwest', 44585.46)
(1319, 1319, 1320, 40.0, 'male', 36.3, 94, 'Yes', 1, 'Yes', 'southwest', 47403.88)
(1324, 1324, 1325, 39.0, 'male', 39.9, 115, 'No', 0, 'Yes', 'southwest', 48173.36)
(1333, 1333, 1334, 44.0, 'male', 36.4, 127, 'No', 1, 'Yes', 'southwest', 51194.56)
(1334, 1334, 1335, 43.0, 'male', 32.8, 125, 'No', 0, 'Yes', 'southwest', 52590.83)

## Q2 Show all records having bmi in range 30 to 45 both inclusive.

In [ ]:
# use this query in sql workbench
# SELECT * FROM insurance_data WHERE bmi BETWEEN 30 AND 45;

In [10]:
# create a cursor object
cursor = con.cursor()

# execute the SQL query
cursor.execute("SELECT * FROM insurance_data WHERE bmi BETWEEN 30 AND 45")

# fetch all the results
results = cursor.fetchall()

# print the results
for row in results:
    print(row)

# # close the cursor and connection
# cursor.close()
# con.close()

(1, 1, 2, 24.0, 'male', 30.1, 87, 'No', 0, 'No', 'southeast', 1131.51)
(2, 2, 3, None, 'male', 33.3, 82, 'Yes', 0, 'No', 'southeast', 1135.94)
(3, 3, 4, None, 'male', 33.7, 80, 'No', 0, 'No', 'northwest', 1136.4)
(4, 4, 5, None, 'male', 34.1, 100, 'No', 0, 'No', 'northwest', 1137.01)
(5, 5, 6, None, 'male', 34.4, 96, 'Yes', 0, 'No', 'northwest', 1137.47)
(6, 6, 7, None, 'male', 37.3, 86, 'Yes', 0, 'No', 'northwest', 1141.45)
(7, 7, 8, 19.0, 'male', 41.1, 100, 'No', 0, 'No', 'northwest', 1146.8)
(8, 8, 9, 20.0, 'male', 43.0, 86, 'No', 0, 'No', 'northwest', 1149.4)
(15, 15, 16, 32.0, 'male', 30.4, 86, 'Yes', 0, 'No', None, 1256.3)
(16, 16, 17, 35.0, 'male', 34.1, 90, 'No', 0, 'No', 'southwest', 1261.44)
(17, 17, 18, 41.0, 'male', 34.4, 84, 'No', 0, 'No', 'southwest', 1261.86)
(18, 18, 19, 49.0, 'male', 35.4, 97, 'Yes', 0, 'No', 'southwest', 1263.25)
(19, 19, 20, 48.0, 'male', 33.3, 91, 'Yes', 0, 'No', 'southeast', 1391.53)
(21, 21, 22, 34.0, 'male', 31.1, 96, 'No', 0, 'No', 'southwest', 1526.31)
(22, 22, 23, 18.0, 'male', 35.5, 100, 'Yes', 0, 'No', 'southeast', 1532.47)
(23, 23, 24, 42.0, 'male', 36.9, 93, 'No', 0, 'No', 'southeast', 1534.3)
(25, 25, 26, 23.0, 'male', 43.0, 86, 'No', 0, 'No', 'northwest', 1149.4)
(28, 28, 29, 58.0, 'female', 31.1, 87, 'No', 0, 'No', 'southeast', 1621.88)
(29, 29, 30, 35.0, 'female', 31.4, 93, 'No', 0, 'No', 'southeast', 1622.19)
(33, 33, 34, 52.0, 'female', 36.9, 81, 'No', 0, 'No', 'southeast', 1629.83)
(34, 34, 35, 43.0, 'female', 38.2, 86, 'Yes', 0, 'No', 'southeast', 1631.67)
(35, 35, 36, 47.0, 'female', 38.3, 93, 'No', 0, 'No', 'southeast', 1631.82)
(38, 38, 39, 28.0, 'female', 39.2, 87, 'No', 0, 'No', 'southeast', 1633.04)
(39, 39, 40, 49.0, 'female', 39.8, 100, 'Yes', 0, 'No', 'southeast', 1633.96)
(40, 40, 41, 29.0, 'female', 40.3, 94, 'No', 0, 'No', 'southeast', 1634.57)
(42, 42, 43, 32.0, 'male', 30.6, 93, 'No', 0, 'No', 'northwest', 1639.56)
(43, 43, 44, 44.0, 'male', 30.6, 82, 'No', 0, 'No', 'northwest', 1639.56)
(44, 44, 45, 37.0, 'male', 35.5, 91, 'No', 0, 'No', 'northwest', 1646.43)
(46, 46, 47, 24.0, 'male', 33.8, 89, 'No', 0, 'No', 'southeast', 1674.63)
(47, 47, 48, 31.0, 'male', 39.5, 80, 'Yes', 0, 'No', 'southwest', 1682.6)
(58, 58, 59, 50.0, 'male', 30.0, 88, 'No', 1, 'No', 'southeast', 1720.35)
(59, 59, 60, 47.0, 'male', 33.8, 90, 'No', 1, 'No', 'southeast', 1725.55)
(60, 60, 61, 49.0, 'male', 35.2, 80, 'Yes', 1, 'No', 'southeast', 1727.54)
(67, 67, 68, 39.0, 'female', 32.9, 99, 'Yes', 0, 'No', 'southwest', 1748.77)
(68, 68, 69, 26.0, 'female', 40.5, 87, 'Yes', 0, 'No', 'southwest', 1759.34)
(71, 71, 72, 48.0, 'male', 32.6, 80, 'Yes', 0, 'No', 'southeast', 1824.29)
(72, 72, 73, 22.0, 'male', 34.4, 98, 'Yes', 0, 'No', 'southwest', 1826.84)
(75, 75, 76, 30.0, 'male', 41.9, 95, 'Yes', 0, 'No', 'southeast', 1837.28)
(78, 78, 79, 42.0, 'female', 31.5, 100, 'No', 0, 'No', 'southeast', 1877.93)
(79, 79, 80, 53.0, 'female', 33.0, 83, 'Yes', 0, 'No', 'southeast', 1880.07)
(80, 80, 81, 26.0, 'female', 33.3, 83, 'Yes', 0, 'No', 'southwest', 1880.49)
(82, 82, 83, 42.0, 'male', 31.3, 98, 'No', 0, 'No', 'northwest', 1909.53)
(83, 83, 84, 43.0, 'male', 36.9, 91, 'Yes', 0, 'No', 'northwest', 1917.32)
(89, 89, 90, 23.0, 'male', 33.0, 80, 'Yes', 1, 'No', 'northwest', 1980.07)
(90, 90, 91, 19.0, 'male', 32.0, 100, 'Yes', 0, 'No', 'southeast', 1981.58)
(91, 91, 92, 20.0, 'male', 40.5, 95, 'No', 0, 'No', 'southeast', 1984.45)
(92, 92, 93, 41.0, 'male', 35.9, 97, 'No', 0, 'No', 'southeast', 1986.93)
(94, 94, 95, 48.0, 'female', 34.6, 99, 'No', 0, 'No', 'southwest', 2020.18)
(95, 95, 96, 54.0, 'female', 34.9, 90, 'No', 0, 'No', 'southeast', 2020.55)
(96, 96, 97, 44.0, 'female', 39.5, 93, 'Yes', 0, 'No', 'southeast', 2026.97)
(98, 98, 99, 47.0, 'male', 32.1, 81, 'No', 0, 'No', 'northwest', 2055.32)
(103, 103, 104, 42.0, 'female', 30.5, 99, 'No', 0, 'No', 'northwest', 2128.43)
(104, 104, 105, 52.0, 'female', 32.1, 94, 'Yes', 0, 'No', 'northwest', 2130.68)
(105, 105, 106, 43.0, 'female', 35.2, 80, 'No', 0, 'No', 'northwest', 2134.9)
(106, 106, 107, 42.0, 'female', 36.6, 90, 'No', 0, 'No', 'northwest', 2136.88)
(108, 108, 109, 26.0, 'female', 37.4, 83, 'Yes', 0, 'No', 'northwest', 2138.07)
(113, 113, 114, 30.0, 'female', 36.0, 80, 'No', 0, 'No', 'southwest', 2166.73)
(118, 118, 119, 58.0, 'female', 30.1, 81, 'Yes', 0, 'No', 'southeast', 2203.47)
(119, 119, 120, 32.0, 'female', 30.3, 94, 'Yes', 0, 'No', 'southeast', 2203.74)
(120, 120, 121, 37.0, 'female', 31.9, 89, 'No', 0, 'No', 'southeast', 2205.98)
(121, 121, 122, 48.0, 'female', 33.2, 97, 'No', 0, 'No', 'southeast', 2207.7)
(122, 122, 123, 52.0, 'female', 35.6, 89, 'No', 0, 'No', 'southeast', 2211.13)
(123, 123, 124, 55.0, 'female', 40.2, 82, 'No', 0, 'No', 'southeast', 2217.47)
(124, 124, 125, 33.0, 'female', 40.3, 94, 'Yes', 0, 'No', 'southeast', 2217.6)
(125, 125, 126, 53.0, 'female', 37.3, 88, 'Yes', 1, 'No', 'southeast', 2219.45)
(128, 128, 129, 31.0, 'male', 31.7, 90, 'No', 0, 'No', 'northwest', 2254.8)
(130, 130, 131, 30.0, 'female', 31.9, 89, 'No', 0, 'No', 'northwest', 2261.57)
(133, 133, 134, 47.0, 'male', 35.4, 95, 'No', 0, 'No', 'southeast', 2322.62)
(136, 136, 137, 40.0, 'male', 32.4, 81, 'No', 1, 'No', 'northwest', 2362.23)
(139, 139, 140, 26.0, 'female', 35.7, 90, 'Yes', 0, 'No', 'northwest', 2404.73)
(140, 140, 141, 47.0, 'male', 35.2, 80, 'No', 1, 'No', 'southwest', 2416.96)
(144, 144, 145, 37.0, 'female', 30.6, 96, 'Yes', 0, 'No', 'southeast', 2459.72)
(146, 146, 147, 47.0, 'female', 34.0, 84, 'No', 0, 'No', 'southeast', 2473.33)
(147, 147, 148, 35.0, 'female', 39.5, 82, 'Yes', 0, 'No', 'southeast', 2480.98)
(149, 149, 150, 22.0, 'male', 30.5, 82, 'No', 0, 'No', 'southwest', 2494.02)
(150, 150, 151, 41.0, 'male', 32.7, 93, 'No', 0, 'No', 'southeast', 2497.04)
(151, 151, 152, 26.0, 'male', 33.7, 99, 'No', 0, 'No', 'southeast', 2498.41)
(154, 154, 155, 33.0, 'male', 35.6, 98, 'No', 0, 'No', 'northwest', 2534.39)
(155, 155, 156, 49.0, 'male', 31.1, 88, 'Yes', 2, 'No', 'southeast', 2566.47)
(159, 159, 160, 30.0, 'female', 30.3, 94, 'Yes', 0, 'No', 'southwest', 2632.99)
(161, 161, 162, 21.0, 'male', 31.4, 91, 'No', 1, 'No', 'northwest', 2643.27)
(163, 163, 164, 28.0, 'male', 38.1, 81, 'Yes', 0, 'No', 'southeast', 2689.5)
(165, 165, 166, 30.0, 'male', 31.1, 91, 'No', 0, 'No', 'northwest', 2699.57)
(169, 169, 170, 41.0, 'female', 31.8, 88, 'Yes', 1, 'No', 'northwest', 2719.28)
(171, 171, 172, 23.0, 'male', 30.6, 96, 'No', 0, 'No', 'southeast', 2727.4)
(172, 172, 173, 34.0, 'female', 39.6, 91, 'Yes', 1, 'No', 'northwest', 2730.11)
(174, 174, 175, 58.0, 'female', 30.4, 85, 'Yes', 0, 'No', 'southeast', 2741.95)
(175, 175, 176, 59.0, 'female', 39.8, 81, 'Yes', 0, 'No', 'northeast', 2755.02)
(178, 178, 179, 60.0, 'female', 32.1, 98, 'No', 2, 'No', 'southeast', 2801.26)
(182, 182, 183, 27.0, 'female', 33.3, 92, 'Yes', 0, 'No', 'northwest', 2855.44)
(186, 186, 187, 25.0, 'female', 34.9, 100, 'No', 0, 'No', 'northeast', 2899.49)
(188, 188, 189, 35.0, 'male', 30.0, 86, 'No', 1, 'No', 'southwest', 2904.09)
(192, 192, 193, 55.0, 'female', 34.5, 87, 'Yes', 0, 'No', 'northwest', 3021.81)
(195, 195, 196, 33.0, 'female', 31.8, 98, 'Yes', 2, 'No', 'southeast', 3056.39)
(196, 196, 197, 30.0, 'male', 30.9, 89, 'Yes', 0, 'No', 'northwest', 3062.51)
(202, 202, 203, 52.0, 'female', 33.1, 87, 'No', 0, 'No', 'southeast', 3171.61)
(203, 203, 204, 35.0, 'female', 33.4, 99, 'No', 0, 'No', 'southwest', 3172.02)
(207, 207, 208, 48.0, 'female', 40.2, 82, 'No', 0, 'No', 'northwest', 3201.25)
(211, 211, 212, 36.0, 'female', 34.0, 88, 'Yes', 1, 'No', 'southeast', 3227.12)
(212, 212, 213, 46.0, 'female', 42.1, 89, 'No', 1, 'No', 'southeast', 3238.44)
(214, 214, 215, 43.0, 'male', 35.4, 86, 'Yes', 0, 'No', 'northeast', 3268.85)
(215, 215, 216, 28.0, 'male', 37.1, 90, 'Yes', 1, 'No', 'southwest', 3277.16)
(217, 217, 218, 23.0, 'male', 33.9, 81, 'No', 1, 'No', 'northwest', 3292.53)
(221, 221, 222, 28.0, 'female', 35.5, 95, 'Yes', 0, 'No', 'southeast', 3366.67)
(226, 226, 227, 35.0, 'female', 38.7, 85, 'No', 2, 'No', 'southeast', 3393.36)
(227, 227, 228, 34.0, 'female', 42.4, 92, 'No', 1, 'No', 'southwest', 3410.32)
(228, 228, 229, 40.0, 'male', 34.8, 81, 'No', 3, 'No', 'southwest', 3443.06)
(229, 229, 230, 42.0, 'male', 38.9, 94, 'No', 1, 'No', 'southeast', 3471.41)
(230, 230, 231, 22.0, 'male', 30.4, 95, 'Yes', 3, 'No', 'southeast', 3481.87)
(232, 232, 233, 49.0, 'male', 32.5, 93, 'Yes', 1, 'No', 'southeast', 3490.55)
(233, 233, 234, 30.0, 'female', 39.3, 92, 'No', 2, 'No', 'southeast', 3500.61)
(236, 236, 237, 59.0, 'female', 34.8, 85, 'Yes', 0, 'No', 'northwest', 3556.92)
(239, 239, 240, 31.0, 'female', 34.8, 88, 'No', 1, 'No', 'southwest', 3578.0)
(240, 240, 241, 47.0, 'female', 33.6, 84, 'Yes', 2, 'No', 'northwest', 3579.83)
(241, 241, 242, 23.0, 'male', 32.7, 82, 'Yes', 3, 'No', 'southwest', 3591.48)
(243, 243, 244, 48.0, 'male', 37.1, 97, 'No', 3, 'No', 'southwest', 3597.6)
(245, 245, 246, 23.0, 'male', 31.4, 88, 'No', 1, 'No', 'southwest', 3659.35)
(247, 247, 248, 31.0, 'male', 30.3, 92, 'No', 0, 'No', 'southeast', 3704.35)
(253, 253, 254, 44.0, 'female', 37.6, 84, 'No', 1, 'No', 'southeast', 3766.88)
(255, 255, 256, 25.0, 'male', 30.9, 86, 'Yes', 0, 'No', 'northeast', 3857.76)
(258, 258, 259, 32.0, 'male', 39.5, 88, 'Yes', 1, 'No', 'southeast', 3875.73)
(259, 259, 260, 18.0, 'male', 30.9, 92, 'No', 2, 'No', 'northwest', 3877.3)
(261, 261, 262, 42.0, 'female', 34.6, 80, 'No', 2, 'No', 'northeast', 3925.76)
(262, 262, 263, 36.0, 'male', 34.2, 96, 'Yes', 0, 'No', 'southeast', 3935.18)
(263, 263, 264, 46.0, 'female', 31.2, 88, 'Yes', 0, 'No', 'northeast', 3943.6)
(265, 265, 266, 38.0, 'female', 31.3, 86, 'Yes', 1, 'No', 'northwest', 3956.07)
(268, 268, 269, 48.0, 'female', 34.2, 99, 'Yes', 2, 'No', 'southwest', 3987.93)
(269, 269, 270, 49.0, 'female', 41.1, 88, 'Yes', 0, 'No', 'southwest', 3989.84)
(270, 270, 271, 46.0, 'female', 44.2, 91, 'Yes', 0, 'No', 'southeast', 3994.18)
(274, 274, 275, 24.0, 'male', 37.3, 99, 'Yes', 2, 'No', 'southeast', 4058.12)
(275, 275, 276, 37.0, 'male', 33.2, 90, 'Yes', 2, 'No', 'northwest', 4058.71)
(276, 276, 277, 23.0, 'male', 30.0, 95, 'Yes', 1, 'No', 'southeast', 4074.45)
(277, 277, 278, 26.0, 'male', 31.5, 95, 'Yes', 1, 'No', 'southwest', 4076.5)
(281, 281, 282, 59.0, 'female', 32.4, 94, 'No', 1, 'No', 'southwest', 4149.74)
(282, 282, 283, 48.0, 'female', 33.3, 100, 'Yes', 1, 'No', 'southeast', 4151.03)
(285, 285, 286, 27.0, 'female', 30.1, 81, 'No', 3, 'No', 'southwest', 4234.93)
(289, 289, 290, 35.0, 'male', 30.3, 80, 'No', 3, 'No', 'southwest', 4260.74)
(290, 290, 291, 49.0, 'male', 44.2, 80, 'No', 2, 'No', 'southeast', 4266.17)
(292, 292, 293, 21.0, 'male', 35.8, 88, 'No', 0, 'No', 'northwest', 4320.41)
(295, 295, 296, 32.0, 'female', 31.1, 88, 'No', 0, 'No', 'southeast', 4347.02)
(296, 296, 297, 25.0, 'female', 33.0, 89, 'Yes', 2, 'No', 'southeast', 4349.46)
(301, 301, 302, 26.0, 'male', 31.5, 88, 'Yes', 0, 'No', 'southwest', 4402.23)
(304, 304, 305, 32.0, 'male', 31.7, 83, 'Yes', 2, 'No', 'northwest', 4433.39)
(305, 305, 306, 34.0, 'male', 32.1, 83, 'Yes', 2, 'No', 'northwest', 4433.92)
(309, 309, 310, 32.0, 'male', 33.0, 94, 'Yes', 3, 'No', 'southeast', 4449.46)
(311, 311, 312, 37.0, 'male', 33.8, 90, 'No', 1, 'No', 'northwest', 4462.72)
(312, 312, 313, 21.0, 'male', 38.4, 87, 'Yes', 2, 'No', 'southeast', 4463.21)
(313, 313, 314, 45.0, 'female', 35.0, 91, 'Yes', 3, 'No', 'northwest', 4466.62)
(315, 315, 316, 44.0, 'male', 33.7, 96, 'No', 4, 'No', 'southeast', 4504.66)
(316, 316, 317, 35.0, 'male', 34.7, 83, 'Yes', 0, 'No', 'southeast', 4518.83)
(319, 319, 320, 26.0, 'male', 42.9, 95, 'Yes', 1, 'No', 'southwest', 4536.26)
(321, 321, 322, 43.0, 'female', 31.4, 99, 'No', 4, 'No', 'southeast', 4561.19)
(325, 325, 326, 31.0, 'female', 30.2, 83, 'No', 3, 'No', 'northwest', 4618.08)
(326, 326, 327, 18.0, 'male', 30.8, 97, 'Yes', 0, 'No', 'southwest', 4646.76)
(328, 328, 329, 26.0, 'male', 37.3, 86, 'Yes', 1, 'No', 'southeast', 4667.61)
(329, 329, 330, 22.0, 'male', 35.2, 87, 'Yes', 2, 'No', 'southwest', 4670.64)
(330, 330, 331, 32.0, 'male', 37.2, 82, 'No', 2, 'No', 'southeast', 4673.39)
(336, 336, 337, 48.0, 'female', 32.7, 95, 'No', 1, 'No', 'northwest', 4738.27)
(339, 339, 340, 19.0, 'male', 30.5, 92, 'Yes', 1, 'No', 'southwest', 4751.07)
(340, 340, 341, 50.0, 'female', 43.1, 98, 'No', 2, 'No', 'southeast', 4753.64)
(341, 341, 342, 46.0, 'male', 38.6, 83, 'Yes', 1, 'No', 'southwest', 4762.33)
(344, 344, 345, 38.0, 'female', 39.8, 85, 'Yes', 1, 'No', 'southeast', 4795.66)
(346, 346, 347, 55.0, 'female', 37.0, 83, 'Yes', 5, 'No', 'southwest', 4830.63)
(347, 347, 348, 43.0, 'male', 31.6, 89, 'No', 3, 'No', 'southeast', 4837.58)
(348, 348, 349, 46.0, 'male', 32.6, 82, 'Yes', 3, 'No', 'southeast', 4846.92)
(352, 352, 353, 28.0, 'male', 35.8, 97, 'No', 2, 'No', 'southeast', 4890.0)
(355, 355, 356, 38.0, 'male', 30.1, 87, 'No', 5, 'No', 'southeast', 4915.06)
(356, 356, 357, 40.0, 'female', 32.1, 95, 'Yes', 2, 'No', 'northwest', 4922.92)
(359, 359, 360, 46.0, 'female', 36.6, 84, 'Yes', 2, 'No', 'southeast', 4949.76)
(363, 363, 364, 25.0, 'female', 33.7, 95, 'No', 1, 'No', 'southwest', 5012.47)
(368, 368, 369, 39.0, 'male', 42.1, 100, 'No', 2, 'No', 'southeast', 5124.19)
(370, 370, 371, 55.0, 'female', 38.8, 86, 'No', 3, 'No', 'southeast', 5138.26)
(371, 371, 372, 33.0, 'female', 31.5, 86, 'No', 1, 'No', 'southeast', 5148.55)
(375, 375, 376, 46.0, 'female', 31.0, 84, 'No', 1, 'No', 'southwest', 5240.77)
(376, 376, 377, 57.0, 'female', 34.2, 93, 'Yes', 1, 'No', 'southeast', 5245.23)
(377, 377, 378, 57.0, 'female', 34.8, 96, 'No', 1, 'No', 'southwest', 5246.05)
(378, 378, 379, 23.0, 'male', 30.8, 89, 'Yes', 3, 'No', 'southwest', 5253.52)
(383, 383, 384, 32.0, 'female', 30.0, 88, 'Yes', 0, 'No', 'northwest', 5272.18)
(385, 385, 386, 49.0, 'female', 30.9, 90, 'Yes', 3, 'No', 'southwest', 5325.65)
(386, 386, 387, 25.0, 'female', 32.8, 81, 'No', 2, 'No', 'northwest', 5327.4)
(388, 388, 389, 32.0, 'male', 30.9, 91, 'No', 1, 'No', 'northwest', 5373.36)
(389, 389, 390, 54.0, 'female', 32.9, 91, 'Yes', 2, 'No', 'southwest', 5375.04)
(390, 390, 391, 44.0, 'male', 33.8, 96, 'No', 1, 'No', 'northwest', 5377.46)
(393, 393, 394, 32.0, 'female', 37.7, 96, 'No', 0, 'No', 'southeast', 5397.62)
(394, 394, 395, 29.0, 'female', 40.2, 85, 'Yes', 0, 'No', 'southeast', 5400.98)
(396, 396, 397, 41.0, 'male', 31.1, 86, 'Yes', 3, 'No', 'northwest', 5425.02)
(397, 397, 398, 27.0, 'male', 37.4, 83, 'No', 3, 'No', 'southeast', 5428.73)
(398, 398, 399, 29.0, 'male', 41.7, 86, 'Yes', 0, 'No', 'southeast', 5438.75)
(404, 404, 405, 23.0, 'male', 31.0, 90, 'No', 1, 'No', 'southwest', 5488.26)
(405, 405, 406, 20.0, 'male', 34.4, 93, 'No', 2, 'No', 'southeast', 5584.31)
(406, 406, 407, 43.0, 'female', 33.3, 94, 'Yes', 1, 'No', 'southeast', 5594.85)
(408, 408, 409, 57.0, 'female', 35.8, 85, 'Yes', 1, 'No', 'northwest', 5630.46)
(409, 409, 410, 54.0, 'female', 32.8, 86, 'Yes', 0, 'No', 'southwest', 5649.72)
(410, 410, 411, 25.0, 'female', 41.8, 95, 'Yes', 0, 'No', 'southeast', 5662.23)
(412, 412, 413, 38.0, 'male', 33.6, 100, 'Yes', 0, 'No', 'southeast', 5699.84)
(414, 414, 415, 20.0, 'male', 40.3, 81, 'Yes', 0, 'No', 'southeast', 5709.16)
(415, 415, 416, 22.0, 'male', 34.8, 89, 'No', 2, 'No', 'northwest', 5729.01)
(416, 416, 417, 23.0, 'male', 42.7, 82, 'No', 0, 'No', 'southeast', 5757.41)
(417, 417, 418, 41.0, 'female', 35.9, 82, 'No', 2, 'No', 'southeast', 5836.52)
(418, 418, 419, 28.0, 'female', 43.3, 90, 'No', 2, 'No', 'southeast', 5846.92)
(421, 421, 422, 51.0, 'female', 36.2, 90, 'Yes', 0, 'No', 'southeast', 5920.1)
(423, 423, 424, 46.0, 'male', 34.3, 89, 'Yes', 3, 'No', 'southeast', 5934.38)
(426, 426, 427, 40.0, 'female', 38.9, 100, 'Yes', 3, 'No', 'southwest', 5972.38)
(428, 428, 429, 34.0, 'female', 30.7, 90, 'No', 1, 'No', 'southeast', 5976.83)
(429, 429, 430, 38.0, 'male', 34.1, 90, 'No', 0, 'No', 'southwest', 5979.73)
(430, 430, 431, 33.0, 'female', 37.3, 95, 'Yes', 2, 'No', 'northwest', 5989.52)
(433, 433, 434, 36.0, 'male', 37.1, 88, 'No', 1, 'No', 'southeast', 6079.67)
(434, 434, 435, 42.0, 'male', 34.7, 97, 'Yes', 2, 'No', 'southwest', 6082.41)
(435, 435, 436, 38.0, 'female', 34.1, 93, 'No', 1, 'No', 'northwest', 6112.35)
(436, 436, 437, 28.0, 'female', 30.5, 82, 'Yes', 3, 'No', 'southeast', 6113.23)
(439, 439, 440, 55.0, 'female', 33.2, 89, 'Yes', 3, 'No', 'northwest', 6128.8)
(441, 441, 442, 39.0, 'female', 31.0, 97, 'No', 0, 'No', 'southeast', 6185.32)
(442, 442, 443, 32.0, 'female', 31.6, 91, 'Yes', 0, 'No', 'southwest', 6186.13)
(443, 443, 444, 32.0, 'female', 38.0, 92, 'No', 3, 'No', 'southwest', 6196.45)
(446, 446, 447, 25.0, 'female', 32.5, 100, 'No', 1, 'No', 'southwest', 6238.3)
(450, 450, 451, 20.0, 'male', 34.2, 89, 'Yes', 1, 'No', 'southeast', 6289.75)
(452, 452, 453, 56.0, 'female', 30.8, 92, 'Yes', 2, 'No', 'southeast', 6313.76)
(453, 453, 454, 58.0, 'female', 37.1, 97, 'No', 3, 'No', 'southeast', 6334.34)
(454, 454, 455, 24.0, 'male', 32.3, 92, 'Yes', 2, 'No', 'southeast', 6338.08)
(456, 456, 457, 28.0, 'male', 31.3, 91, 'No', 0, 'No', 'northwest', 6358.78)
(457, 457, 458, 50.0, 'female', 42.9, 98, 'No', 3, 'No', 'northwest', 6360.99)
(458, 458, 459, 34.0, 'female', 40.6, 98, 'No', 1, 'No', 'northwest', 6373.56)
(467, 467, 468, 59.0, 'female', 37.9, 91, 'No', 0, 'No', 'southwest', 6474.01)
(471, 471, 472, 29.0, 'female', 36.3, 83, 'No', 3, 'No', 'southeast', 6551.75)
(473, 473, 474, 48.0, 'female', 33.0, 99, 'No', 0, 'No', 'northwest', 6571.02)
(474, 474, 475, 55.0, 'female', 34.8, 80, 'Yes', 2, 'No', 'southwest', 6571.54)
(476, 476, 477, 45.0, 'male', 34.1, 96, 'No', 1, 'No', 'southeast', 6600.21)
(478, 478, 479, 38.0, 'male', 41.2, 81, 'Yes', 1, 'No', 'southeast', 6610.11)
(481, 481, 482, 20.0, 'male', 33.4, 89, 'Yes', 5, 'No', 'southeast', 6653.79)
(483, 483, 484, 48.0, 'male', 42.4, 92, 'Yes', 5, 'No', 'southwest', 6666.24)
(490, 490, 491, 54.0, 'female', 32.2, 89, 'No', 1, 'No', 'southwest', 6775.96)
(491, 491, 492, 40.0, 'female', 36.1, 80, 'No', 1, 'No', 'southeast', 6781.35)
(492, 492, 493, 27.0, 'male', 30.9, 91, 'No', 3, 'No', 'northwest', 6796.86)
(495, 495, 496, 46.0, 'male', 30.1, 85, 'Yes', 1, 'No', 'southwest', 6849.03)
(497, 497, 498, 45.0, 'male', 32.2, 100, 'Yes', 2, 'No', 'southwest', 6875.96)
(501, 501, 502, 40.0, 'male', 39.5, 88, 'No', 0, 'No', 'northwest', 6948.7)
(503, 503, 504, 40.0, 'male', 32.3, 87, 'Yes', 2, 'No', 'northwest', 6986.7)
(506, 506, 507, 56.0, 'female', 32.9, 84, 'Yes', 0, 'No', 'southeast', 7050.02)
(512, 512, 513, 46.0, 'male', 34.3, 89, 'No', 1, 'No', 'southeast', 7147.47)
(514, 514, 515, 40.0, 'male', 38.1, 91, 'No', 1, 'No', 'southeast', 7152.67)
(516, 516, 517, 48.0, 'male', 35.8, 82, 'Yes', 2, 'No', 'southwest', 7160.09)
(517, 517, 518, 18.0, 'male', 36.0, 93, 'No', 2, 'No', 'southeast', 7160.33)
(518, 518, 519, 19.0, 'male', 37.2, 96, 'Yes', 2, 'No', 'southeast', 7162.01)
(520, 520, 521, 21.0, 'male', 35.3, 96, 'No', 3, 'No', 'southwest', 7196.87)
(522, 522, 523, 34.0, 'female', 31.9, 94, 'No', 2, 'No', 'northwest', 7209.49)
(526, 526, 527, 20.0, 'male', 30.6, 90, 'No', 2, 'No', 'northwest', 7256.72)
(527, 527, 528, 39.0, 'male', 34.2, 81, 'Yes', 2, 'No', 'northwest', 7261.74)
(528, 528, 529, 48.0, 'male', 37.1, 81, 'Yes', 2, 'No', 'northwest', 7265.7)
(533, 533, 534, 32.0, 'female', 33.1, 94, 'Yes', 0, 'No', 'southwest', 7345.08)
(534, 534, 535, 60.0, 'female', 35.6, 80, 'No', 1, 'No', 'southeast', 7345.73)
(535, 535, 536, 37.0, 'female', 35.3, 100, 'No', 0, 'No', 'southwest', 7348.14)
(536, 536, 537, 55.0, 'female', 31.6, 91, 'No', 1, 'No', 'southeast', 7358.18)
(537, 537, 538, 26.0, 'female', 37.1, 88, 'No', 2, 'No', 'southwest', 7371.77)
(538, 538, 539, 49.0, 'female', 34.1, 82, 'No', 3, 'No', 'southwest', 7418.52)
(541, 541, 542, 46.0, 'male', 30.2, 80, 'No', 1, 'No', 'southwest', 7441.05)
(542, 542, 543, 19.0, 'male', 32.6, 94, 'Yes', 2, 'No', 'southwest', 7441.5)
(543, 543, 544, 31.0, 'female', 36.2, 96, 'No', 1, 'No', 'northwest', 7443.64)

## Q3 Show minimum and maximum bloodpressure of diabetic patient who smokes. Make column names as MinBP and MaxBP respectively.

In [ ]:
# use this query in sql workbench
# SELECT MIN(bloodpressure) AS MinBP, MAX(bloodpressure) AS MaxBP 
# FROM insurance_data 
# WHERE diabetic='yes' AND smoker='yes';

In [11]:
# create a cursor object
cursor = con.cursor()

# execute the SQL query
cursor.execute("SELECT MIN(bloodpressure) AS MinBP, MAX(bloodpressure) AS MaxBP FROM insurance_data WHERE diabetic='yes' AND smoker='yes'")

# fetch the result
result = cursor.fetchone()

# print the result
print("Minimum Blood Pressure:", result[0])
print("Maximum Blood Pressure:", result[1])

# # close the cursor and connection
# cursor.close()
# con.close()

Minimum Blood Pressure: 80
Maximum Blood Pressure: 140

## Q4 Find no of unique patients who are not from southwest region.

In [ ]:
# use this query in sql workbench
# SELECT COUNT(DISTINCT PatientID) 
# FROM insurance_data 
# WHERE region != 'southwest';

In [12]:
# create a cursor object
cursor = con.cursor()

# execute the SQL query
cursor.execute("SELECT COUNT(DISTINCT PatientID) as unique_patients FROM insurance_data WHERE region <> 'southwest'")

# fetch the result
result = cursor.fetchone()

# print the result
print("Number of unique patients who are not from the southwest region:", result[0])

# # close the cursor and connection
# cursor.close()
# con.close()

Number of unique patients who are not from the southwest region: 1023

## Q5 Total claim amount from male smoker.

In [ ]:
# use this query in sql workbench
# SELECT SUM(claim) 
# FROM insurance_data 
# WHERE gender = 'male' AND smoker = 'yes';

In [13]:
# create a cursor object
cursor = con.cursor()

# execute the SQL query
cursor.execute("SELECT SUM(claim) as total_claim_amount FROM insurance_data WHERE gender = 'male' AND smoker = 'yes'")

# fetch the result
result = cursor.fetchone()

# print the result
print("Total claim amount from male smokers:", result[0])

# # close the cursor and connection
# cursor.close()
# con.close()

Total claim amount from male smokers: 5253678.99

## Q6 Select all records of south region.

In [ ]:
# use this query in sql workbench
# SELECT * FROM insurance_data WHERE region = 'south';

In [14]:
# create a cursor object
cursor = con.cursor()

# execute the SQL query
cursor.execute("SELECT * FROM insurance_data WHERE region = 'south'")

# fetch the result
result = cursor.fetchall()

# print the result
for row in result:
  print(row)

# # close the cursor and connection
# cursor.close()
# con.close()

## Q7 No of patient having normal blood pressure. Normal range[90-120]

In [ ]:
# use this query in sql workbench
# SELECT COUNT(*) as normal_bp_count 
# FROM insurance_data 
# WHERE bloodpressure >= 90 AND bloodpressure <= 120;

In [15]:

# create a cursor object
cursor = con.cursor()

# execute the SQL query
cursor.execute("SELECT COUNT(*) as normal_bp_count FROM insurance_data WHERE bloodpressure >= 90 AND bloodpressure <= 120")

# fetch the result
result = cursor.fetchone()

# print the result
print("Number of patients with normal blood pressure:", result[0])

# # close the cursor and connection
# cursor.close()
# con.close()

Number of patients with normal blood pressure: 758

## Q8 No of pateint below 17 years of age having normal blood pressure as per below formula -

### BP normal range = 80+(age in years × 2) to 100 + (age in years × 2)

In [ ]:
# use this query in sql workbench
# SELECT COUNT(*) as normal_bp_count 
# FROM insurance_data 
# WHERE age < 17 AND bloodpressure >= (80 + (age * 2)) AND bloodpressure <= (100 + (age * 2));

In [16]:
# create a cursor object
cursor = con.cursor()

# execute the SQL query
cursor.execute("SELECT COUNT(*) as normal_bp_count FROM insurance_data WHERE age < 17 AND bloodpressure >= (80 + (age * 2)) AND bloodpressure <= (100 + (age * 2))")

# fetch the result
result = cursor.fetchone()

# print the result
print("Number of patients below 17 years of age with normal blood pressure:", result[0])

# # close the cursor and connection
# cursor.close()
# con.close()

Number of patients below 17 years of age with normal blood pressure: 0

## Q9 What is the average claim amount for non-smoking female patients who are diabetic?

In [ ]:
SELECT AVG(claim) AS avg_claim_amount
FROM insurance_data 
WHERE gender = 'female' AND smoker = 'no' AND diabetic = 'yes';

In [72]:
# create a cursor object
cursor = con.cursor()

# execute the SQL query
cursor.execute("SELECT round(AVG(claim),2) AS avg_claim_amount FROM insurance_data WHERE gender = 'female' AND smoker = 'no' AND diabetic = 'yes'")

# fetch the result
result = cursor.fetchone()

# print the result
print("Average claim amount for non-smoking female patients who are diabetic:", result[0])

# # close the cursor and connection
# cursor.close()
# con.close()

Average claim amount for non-smoking female patients who are diabetic: 8593.75

## Q10 Write a SQL query to update the claim amount for the patient with PatientID = 1234 to 5000.

In [ ]:
# use this query in sql workbench
# UPDATE insurance_data SET claim = 5000 WHERE PatientID = 1234;

In [17]:
# create a cursor object
cursor = con.cursor()

# execute the SQL query
cursor.execute("UPDATE insurance_data SET claim = 5000 WHERE PatientID = 1234")

# commit the changes to the database
con.commit()

# print the number of rows affected
print(cursor.rowcount, "record(s) affected")

# # close the cursor and connection
# cursor.close()
# con.close()

1 record(s) affected

## Q11 Write a SQL query to delete all records for patients who are smokers and have no children.

In [ ]:
# use this query in sql workbench
# DELETE FROM insurance_data WHERE smoker = 'yes' AND children = 0;

In [18]:

# create a cursor object
cursor = con.cursor()

# execute the SQL query
cursor.execute("DELETE FROM insurance_data WHERE smoker = 'yes' AND children = 0")

# commit the changes to the database
con.commit()

# print the number of rows affected
print(cursor.rowcount, "record(s) deleted")

# # close the cursor and connection
# cursor.close()
# con.close()

115 record(s) deleted